Extract API bundle and add Baseline plugin
orbinson/aem-groovy-console pull request #31
Opened 2023-01-03 12:58 UTC by royteeuwen

2023-01-03 13:00 UTC, royteeuwen commented
Will solve https://github.com/orbinson/aem-groovy-console/issues/28

2023-01-03 13:19 UTC, bdhoine requested changes

2023-01-03 13:19 UTC, bdhoine commented on api/src/main/groovy/be/orbinson/aem/groovy/console/api/context/ServletScriptContext.groovy
> +import java.util.function.Consumer
should this import be added?

2023-01-03 13:19 UTC, bdhoine commented on api/src/main/groovy/be/orbinson/aem/groovy/console/api/context/impl/package-info.groovy
> +@org.osgi.annotation.versioning.Version("1.0.0")
should this be inline with the maven version as we will only bump if needed?

2023-01-03 13:19 UTC, bdhoine commented on api/src/main/groovy/be/orbinson/aem/groovy/console/notification/EmailNotificationService.groovy
> +import org.osgi.annotation.versioning.ProviderType
ProviderType not used

2023-01-04 22:22 UTC, bdhoine approved these changes

2023-01-04 22:22 UTC, bdhoine commented on CHANGELOG.md
> +- Split the bundle into an API and Core bundle and add package versions.
```suggestion
- Split the bundle into an API and Core bundle and add package versions: [#31](https://github.com/orbinson/aem-groovy-console/issues/31)
```

2023-01-04 22:22 UTC, bdhoine commented on CHANGELOG.md
> +- Use the bnd-baseline-maven-plugin to verify when to upgrade the package versions
```suggestion
- Use the bnd-baseline-maven-plugin to verify when to upgrade the package versions: [#31](https://github.com/orbinson/aem-groovy-console/issues/31)
```

2023-01-04 22:23 UTC, merged